### PR TITLE
Slice Mod, Merge Lists Mod, code cleanups

### PR DESCRIPTION
**Pull request by TheMonDon**
Upload/change slice mod
Create merge lists mod
Minior cleanup in other mods

### CODE REVIEW

**Comment by TheMonDon** [comment]
Uploaded delete_message action, fixed it breaking everything after it with no perms.

**Comment by TheMonDon** [comment]
remove delete message as im not sure it works how i intended it to but idk why anything i did would make a difference

**Comment by TheMonDon** [comment]
Uploaded my music modules

**Comment by generalwrex** [comment]
You're not telling me that things have been 100% tested mon. i will not accept them unless everything has been tested

**Comment by TheMonDon** [comment]
Sir generalwrex everything has been 100% tested by yours truly

**Pull request merged**
