### PR TITLE
Update and rename find_member.js to find_mem_or_user_MOD.js

### PR DESCRIPTION
**Pull request by TotallynotTwo**
I added two options in the action to choose between finding a user (all servers) or finding a member (current server).

Note: I didn't know what to name it so just rename it if you can figure out a better name.

### CODE REVIEW

**Comment by LasseNiermann** [comment]
Huh.
Any opinions on this @everyone?

**Comment by LasseNiermann** [comment]
So, we cannot change the name of the action. It will be incompatible with all current projects.
Furthermore: WHY? I do not really see a common use for this.

**Comment by TotallynotTwo** [comment]
> So, we cannot change the name of the action. It will be incompatible with all current projects.
> Furthermore: WHY? I do not really see a common use for this.

there's multiple uses for this... One is sending a message to a user that shares a common server w/ the bot but is not in the current server you're sending the command message in. Another way you can use this is for a global system that can retrieve the user object from just a users id. If you still don't see a use for this then you can just close this pr and I'll send the mod over to the person that suggested this.

**Comment by MrG0ld** [comment]
Rename to "find_member.js" again

**Pull request merged**
