### PR TITLE
Added Call Command or Event

### PR DESCRIPTION
**Pull request by ZockerNico**
This is a modified version of the original action which allows you to insert a specific id.

### CODE REVIEW

**Comment by LasseNiermann** [comment]
Hey, I will not merge this pull request yet. 
Your new option to insert a specific ID doesn't seem to be that important right now. I would prefer to wait for the communities opinion. If they want it we add it. The only use I can imagine of right now would be to do something like `!call <ID>`.

I’ll check this again in a few days 👍🏻

**Comment by ZockerNico** [comment]
That's the reason Lasse. Someone asked me private if this would be able...
I saw that it's impossible via Run Script and created this mod.

**Comment by LasseNiermann** [comment]
Yep. But is it a "must have mod" for all users? Probably not. Might be added to the alternative mods I guess.

**Comment by ZockerNico** [comment]
Ok. Could you move it? I would have to create a new pull request...

**Comment by ZockerNico** [comment]
NVM, got it to work 😉

**Pull request merged**
